### ISSUE TITLE
charger plug in has 2 sounds 

### ISSUE THREAD

**Issue by Ducksucc1337** [Litteeen/Nevve#1]
I just installed this amazing tweak and when i was changing some stuff I realized that when i plug in my phone (iphone 6s unc0ver 12.4) it makes the default sound plus the one you pick

**Comment by Litteeen** [comment]
Thanks for noticing, i’ll push an update today to fix it 🤗---- On Thu, 13 Feb 2020 07:59:38 +0100  notifications@github.com<notifications@github.com> wrote ----I just installed this amazing tweak and when i was changing some stuff I realized that when i plug in my phone (iphone 6s unc0ver 12.4) it makes the default sound plus the one you pick

**Comment by Litteeen** [comment]
This feature has been removed, please use malipo instead 😇
