### ISSUE TITLE
Folder Open plays both folder open and icon tap sound

### ISSUE THREAD

**Issue by rdc74656** [Litteeen/Nevve#2]
As description, when tapping a folder, both the folder open and icon tap sound plays.
Could a different sound be assignable to the folder being closed opposed to having the same sound as folder opening.
Nevve 1.0.2 iPhone 7plus iOS 12.4

**Comment by Litteeen** [comment]
I will try it myself now and fix it as soon as possible ^^






---- On Fri, 14 Feb 2020 12:13:35 +0100 rdc74656 <notifications@github.com> wrote ----


As description, when tapping a folder, both the folder open and icon tap sound plays.
 Could a different sound be assignable to the folder being closed opposed to having the same sound as folder opening.
 Nevve 1.0.2 iPhone 7plus iOS 12.4

**Comment by Litteeen** [comment]
has been fixed in 1.0.3 🤗
