### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by rdc74656** [Litteeen/Nevve#4]
(On my device atleast) Accessing spotlight sound is not playing.

Nevve 1.0.3 iphone 7plus ios 12.4

**Comment by Litteeen** [comment]
could you try disabling other tweaks with iCleaner please? It works fine on my iX 13.3, i7 13.3 and i6s 12.4 c:

**Comment by rdc74656** [comment]
I’ve not really got anymore tweaks that affect spotlight access...only sound tweaks I’ve got are malipo, unplugged, unlock sound, cabello, bannersounds12.

**Comment by Litteeen** [comment]
Did you get it to work?

**Comment by Litteeen** [comment]
Didn’t get any reply back so i suppose it’s been fixed/you got it working/something else
